import { NextRequest, NextResponse } from 'next/server'
import { stripe } from '@/lib/stripe'
import { createServiceClient } from '@/lib/supabase/server'
import type Stripe from 'stripe'
import { Resend } from 'resend'
import QRCode from 'qrcode'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(req: NextRequest) {
  const body = await req.text()
  const sig = req.headers.get('stripe-signature')!

  let event: Stripe.Event
  try {
    event = stripe.webhooks.constructEvent(body, sig, process.env.STRIPE_WEBHOOK_SECRET!)
  } catch (err) {
    console.error('Webhook signature error:', err)
    return NextResponse.json({ error: 'Invalid signature' }, { status: 400 })
  }

  if (event.type === 'checkout.session.completed') {
    const session = event.data.object as Stripe.Checkout.Session
    const meta = session.metadata!

    try {
      const supabase = await createServiceClient()
      const quantity = parseInt(meta.quantity || '1')
      const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'

      // Upsert person
      const { data: person, error: personErr } = await supabase
        .from('people')
        .upsert({
          first_name: meta.first_name,
          last_name: meta.last_name,
          email: meta.email,
          phone: meta.phone,
          role_type: 'audience',
          position: 'Audience',
        }, { onConflict: 'email' })
        .select()
        .single()

      if (personErr) throw personErr

      // Create payment record
      const { error: paymentErr } = await supabase.from('payments').insert({
        person_id: person.id,
        amount: session.amount_total,
        method: 'stripe',
        status: 'confirmed',
        external_reference: session.id,
        notes: `Stripe checkout - ${TICKET_LABELS[meta.ticket_type]} x${quantity}`,
      })
      if (paymentErr) throw paymentErr

      // Create tickets — each gets a unique qr_token auto-generated by the DB
      const tickets = Array.from({ length: quantity }, () => ({
        person_id: person.id,
        type: meta.ticket_type,
        status: 'paid',
        assigned_at: new Date().toISOString(),
      }))
      const { data: createdTickets, error: ticketErr } = await supabase
        .from('tickets')
        .insert(tickets)
        .select()
      if (ticketErr) throw ticketErr

      // Generate QR code image for each ticket
      const qrSections = await Promise.all(
        (createdTickets || []).map(async (ticket, i) => {
          const scanUrl = `${appUrl}/scan/${ticket.qr_token}`
          const qrDataUrl = await QRCode.toDataURL(scanUrl, { width: 250, margin: 2 })
          return `
            <div style="text-align:center;margin:20px 0;padding:20px;border:1px solid #eee;border-radius:8px;">
              <p style="margin:0 0 8px;font-weight:600;color:#333;">Ticket ${i + 1} of ${quantity} — ${TICKET_LABELS[meta.ticket_type]}</p>
              <img src="${qrDataUrl}" alt="QR Code" style="width:200px;height:200px;" />
              <p style="margin:8px 0 0;font-size:12px;color:#999;">One-time use only</p>
            </div>
          `
        })
      )

      // Send confirmation email with QR codes
      await resend.emails.send({
        from: process.env.EMAIL_FROM || 'onboarding@resend.dev',
        to: meta.email,
        subject: 'Your Raas Rodeo Ticket — QR Code Inside',
        html: `
          <div style="font-family:sans-serif;max-width:600px;margin:0 auto;padding:24px;">
            <h2 style="color:#333;">You're in, ${meta.first_name}! 🎉</h2>
            <p style="color:#555;">Your ticket purchase is confirmed. Show the QR code(s) below at the door to check in.</p>
            <table style="width:100%;margin:16px 0;border-collapse:collapse;">
              <tr><td style="padding:6px 0;color:#777;">Ticket type</td><td style="padding:6px 0;font-weight:600;">${TICKET_LABELS[meta.ticket_type]}</td></tr>
              <tr><td style="padding:6px 0;color:#777;">Quantity</td><td style="padding:6px 0;font-weight:600;">${quantity}</td></tr>
              <tr><td style="padding:6px 0;color:#777;">Total paid</td><td style="padding:6px 0;font-weight:600;">$${((session.amount_total || 0) / 100).toFixed(2)}</td></tr>
            </table>
            ${qrSections.join('')}
            <p style="color:#999;font-size:13px;margin-top:24px;">Each QR code is valid for one scan only. Do not share your QR code. See you at the show!</p>
            <p style="color:#999;font-size:13px;">— The Raas Rodeo Team</p>
          </div>
        `,
      })
    } catch (err) {
      console.error('Webhook processing error:', err)
      return NextResponse.json({ error: 'Processing failed' }, { status: 500 })
    }
  }

  return NextResponse.json({ received: true })
}

const TICKET_LABELS: Record<string, string> = {
  competitor: 'Competitor Ticket',
  ff: 'Friends & Family Ticket',
  public: 'General Admission',
}
